# 代理客户端和核心
# luci-app-openclash
# luci-app-passwall
# luci-app-passwall_INCLUDE_Xray
# luci-app-passwall_INCLUDE_Hysteria
# luci-app-passwall_INCLUDE_SingBox
# luci-app-passwall_INCLUDE_Shadowsocks_Rust_Client
# luci-app-passwall_INCLUDE_V2ray_Geodata
# luci-app-passwall_INCLUDE_V2ray_Geoview
# socat

# 网络和远程访问
# luci-mod-network
# luci-app-ddns
# luci-app-frpc
# luci-app-openvpn-server
# luci-app-openvpn
luci-app-sqm
# luci-proto-wireguard
# xl2tpd

# 监控和恢复
# luci-app-autoreboot

# 主题
# luci-theme-argon

# USB 存储和文件系统
# kmod-usb-storage
# kmod-usb-storage-uas
# kmod-usb3
# kmod-fs-ext4
# kmod-fs-vfat
# kmod-fs-exfat
# kmod-fs-ntfs3
# fdisk
# block-mount

# 校园网和常用工具
# luci-app-scutclient
# luci-app-ttyd
# luci-app-vlmcsd
# scut-unicom
# bind-host

# 常用可选插件（删除行首 # 即可启用）
# luci-app-nlbwmon
# luci-app-watchcat
# luci-app-wol
# luci-app-hd-idle
# luci-app-samba4
# luci-app-upnp
# luci-app-mwan3
