# 代理客户端和核心
# luci-app-openclash
# luci-app-passwall
# luci-app-passwall_INCLUDE_Xray
# luci-app-passwall_INCLUDE_Hysteria
# luci-app-passwall_INCLUDE_SingBox
# luci-app-passwall_INCLUDE_Shadowsocks_Rust_Client
# luci-app-passwall_INCLUDE_V2ray_Geodata
# luci-app-passwall_INCLUDE_V2ray_Geoview
# socat

# 网络和远程访问
# luci-mod-network
# luci-app-ddns
# luci-app-frpc
# luci-app-openvpn-server
# luci-app-openvpn
# luci-app-sqm
# luci-proto-wireguard
# xl2tpd

# 监控和恢复
# luci-app-autoreboot

# 主题
# luci-theme-argon

# USB 存储和文件系统
# kmod-usb-storage
# kmod-usb-storage-uas
# kmod-usb3
# kmod-fs-ext4
# kmod-fs-vfat
# kmod-fs-exfat
# kmod-fs-ntfs3
# fdisk
# block-mount

# 校园网和常用工具
# luci-app-scutclient
# luci-app-ttyd
# luci-app-vlmcsd
# scut-unicom
# bind-host

# 常用可选插件（删除行首 # 即可启用）
# luci-app-nlbwmon
# luci-app-watchcat
# luci-app-wol
# luci-app-hd-idle
# luci-app-samba4
# luci-app-upnp
# luci-app-mwan3
 # ========== Zerotier 相关 ==========
 CONFIG_PACKAGE_kmod-tun=y
 CONFIG_PACKAGE_libatomic1=y
 CONFIG_PACKAGE_libstdcpp6=y
 CONFIG_PACKAGE_ip-full=y
 CONFIG_PACKAGE_ip-tiny=n
 # ========== 【常用系统依赖库，解决插件缺库】25.10专用 ==========
 CONFIG_PACKAGE_libopenssl=y
 CONFIG_PACKAGE_libopenssl-util=y
 CONFIG_PACKAGE_libcurl=y
 CONFIG_PACKAGE_libjson-c=y
 CONFIG_PACKAGE_libuci=y
 CONFIG_PACKAGE_libubus=y
 CONFIG_PACKAGE_libubox=y
 CONFIG_PACKAGE_libmnl=y
 CONFIG_PACKAGE_libnftnl=y
 CONFIG_PACKAGE_libpcap=y
 CONFIG_PACKAGE_libxml2=y
 CONFIG_PACKAGE_libzstd=y
 CONFIG_PACKAGE_liblzma=y
 CONFIG_PACKAGE_libbz2=y
# ========== 内核模块通用依赖 ==========
 CONFIG_PACKAGE_kmod-nft-tproxy=y
 CONFIG_PACKAGE_kmod-inet-diag=y
 CONFIG_PACKAGE_kmod-ipt-nat6=y
 CONFIG_PACKAGE_kmod-ipt-ipset=y
 CONFIG_PACKAGE_kmod-ipt-conntrack=y
 CONFIG_PACKAGE_kmod-ipt-filter=y
